In [1]:
import torch

In [4]:
n = 5
A = torch.randn((n, n))

In [9]:
A

tensor([[-0.9056,  0.3634, -0.9871,  0.0696,  0.5085],
        [-0.2655,  0.0462, -1.2180, -1.2400, -0.2506],
        [-0.3850, -1.7651,  0.0512, -0.5186,  0.5255],
        [ 0.1223,  1.0005, -0.4731,  0.6372, -0.0104],
        [ 0.3230,  1.0168, -0.0418,  0.1864,  1.4153]])

In [17]:
U, S, Vh = torch.linalg.svd(A)
V = Vh.T

# Isolating Singular Values
To isolate singular value $\sigma_i$ one multiplies vectors $u_i$ and $v_i$ from both sides:
$$ \sigma_i(A) = u_i^T A v_i $$

In [10]:
i = 2
S[i]

tensor(1.5714)

In [18]:
def col(X, i):
    return X[:, i]

In [19]:
col(U, i) @ A @ col(V, i)

tensor(1.5714)

# Sum of Submatrices
The SVD can also be represented as a sum: $$ A = \sum_i \sigma_i u_i v_j^T $$
Note that this is an outer product of the vectors $u_i$ and $v_i$ rather than a dot product. Therefore, each summand is a matrix of size $n \times n$

In [26]:
def submatrix(i):
    ui = col(U, i)
    vi = col(V, i)
    return S[i] * torch.outer(ui, vi)

In [27]:
assert submatrix(0).shape == (n, n)

In [28]:
sms = [submatrix(i) for i in range(n)]

In [30]:
sum(sms)

tensor([[-0.9056,  0.3634, -0.9871,  0.0696,  0.5085],
        [-0.2655,  0.0462, -1.2180, -1.2400, -0.2506],
        [-0.3850, -1.7651,  0.0512, -0.5186,  0.5255],
        [ 0.1223,  1.0005, -0.4731,  0.6372, -0.0104],
        [ 0.3230,  1.0168, -0.0418,  0.1864,  1.4153]])

In [31]:
A

tensor([[-0.9056,  0.3634, -0.9871,  0.0696,  0.5085],
        [-0.2655,  0.0462, -1.2180, -1.2400, -0.2506],
        [-0.3850, -1.7651,  0.0512, -0.5186,  0.5255],
        [ 0.1223,  1.0005, -0.4731,  0.6372, -0.0104],
        [ 0.3230,  1.0168, -0.0418,  0.1864,  1.4153]])