In [1]:
import torch
from torch import randn

# Vector-Matrix-Vector product

In [2]:
m, n = 4, 5
torch.manual_seed(0)
x = randn(m)
A = randn(m, n)
y = randn(n)

In [3]:
x

tensor([ 1.5410, -0.2934, -2.1788,  0.5684])

In [4]:
x @ A @ y

tensor(-2.8791)

In [5]:
torch.einsum("m, mn, n -> ", x, A, y)

tensor(-2.8791)

# Multiplicative Attention

In [6]:
m = 3  # num timesteps
b = 2  # num batches
h = 4  # hidden layer dim

In [7]:
torch.manual_seed(0)
H_encs = randn(b, 2*h, m)
W = randn(h, 2*h)
h_decs = randn(b, h)

In [8]:
e_ts = []
for i in range(b):
    h_enc = H_encs[i, ...]
    h_dec = h_decs[i, ...]
    e_t = h_dec @ W @ h_enc
    e_ts.append(e_t)
e_ts = torch.stack(e_ts)

In [9]:
e_ts

tensor([[-1.7803,  1.0749,  2.5256],
        [ 1.5803, -1.1913, -1.1185]])

In [10]:
torch.einsum("bh, hd, bdm -> bm", h_decs, W, H_encs)

tensor([[-1.7803,  1.0749,  2.5256],
        [ 1.5803, -1.1913, -1.1185]])

holy shit! 🔥 Einsum returns the same result without looping etc.